// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaxFlow.Infrastructure.Persistence;

#nullable disable

namespace TaxFlow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TaxFlowDbContext))]
    [Migration("20260505100459_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Domain.Contracts.AttributeDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<int>("DataType")
                        .HasColumnType("integer")
                        .HasColumnName("data_type");

                    b.Property<Guid?>("EnumDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("enum_definition_id");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("key");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("label");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("RegexPattern")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("regex_pattern");

                    b.Property<Guid>("asset_type_id")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_type_id");

                    b.HasKey("Id");

                    b.HasIndex("EnumDefinitionId")
                        .HasDatabaseName("ix_attribute_definitions_enum_definition_id");

                    b.HasIndex("asset_type_id", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_attribute_definitions_asset_key");

                    b.ToTable("attribute_definitions", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Contracts.EnumDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("key");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("label");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ux_enum_definitions_key");

                    b.ToTable("enum_definitions", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Contracts.EnumItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("EnumDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("enum_definition_id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("label");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.HasKey("Id");

                    b.HasIndex("EnumDefinitionId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_enum_items_definition_code");

                    b.ToTable("enum_items", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Tax.Assets.AssetType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("Deleted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("LastDeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_deleted_on");

                    b.Property<Guid?>("LastDeletedby")
                        .HasColumnType("uuid")
                        .HasColumnName("last_deleted_by");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTimeOffset?>("LastRecovered")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_recovered");

                    b.Property<Guid?>("LastRecoveredBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_recovered_by");

                    b.Property<int>("LiquidationMode")
                        .HasColumnType("integer")
                        .HasColumnName("liquidation_mode");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_asset_types_name");

                    b.ToTable("asset_types", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Tax.Calculation.TaxRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Expression")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("expression");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("key");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("label");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.Property<Guid>("asset_type_id")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_type_id");

                    b.HasKey("Id");

                    b.HasIndex("asset_type_id", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_tax_rules_asset_key");

                    b.ToTable("tax_rules", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Tax.Obligations.DeclarationDeadline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConditionExpression")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("condition_expression");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<int>("DeclarationType")
                        .HasColumnType("integer")
                        .HasColumnName("declaration_type");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<int?>("FiscalYear")
                        .HasColumnType("integer")
                        .HasColumnName("fiscal_year");

                    b.Property<string>("FormReference")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("form_reference");

                    b.Property<string>("GracePeriod")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("grace_period");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("key");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("label");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("LocalizedDescription")
                        .HasColumnType("jsonb")
                        .HasColumnName("localized_description");

                    b.Property<string>("LocalizedLabel")
                        .HasColumnType("jsonb")
                        .HasColumnName("localized_label");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<int?>("Period")
                        .HasColumnType("integer")
                        .HasColumnName("period");

                    b.Property<int>("Periodicity")
                        .HasColumnType("integer")
                        .HasColumnName("periodicity");

                    b.Property<int>("Regime")
                        .HasColumnType("integer")
                        .HasColumnName("regime");

                    b.Property<bool>("RequiresDocuments")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_documents");

                    b.Property<Guid>("schedule_id")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.HasKey("Id");

                    b.HasIndex("schedule_id");

                    b.ToTable("declaration_deadlines", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Tax.Obligations.LegalReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Article")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("article");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateOnly?>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<DateOnly?>("PublicationDate")
                        .HasColumnType("date")
                        .HasColumnName("publication_date");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reference");

                    b.Property<int>("TextType")
                        .HasColumnType("integer")
                        .HasColumnName("text_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.ToTable("legal_references", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Tax.Obligations.PaymentDeadline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowsPartialPayment")
                        .HasColumnType("boolean")
                        .HasColumnName("allows_partial_payment");

                    b.Property<string>("ConditionExpression")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("condition_expression");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<int?>("FiscalYear")
                        .HasColumnType("integer")
                        .HasColumnName("fiscal_year");

                    b.Property<decimal?>("FixedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("fixed_amount");

                    b.Property<decimal>("Fraction")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("fraction");

                    b.Property<string>("GracePeriod")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("grace_period");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("key");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("label");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("LinkedDeclarationKey")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("linked_declaration_key");

                    b.Property<string>("LocalizedDescription")
                        .HasColumnType("jsonb")
                        .HasColumnName("localized_description");

                    b.Property<string>("LocalizedLabel")
                        .HasColumnType("jsonb")
                        .HasColumnName("localized_label");

                    b.Property<decimal?>("MinimumPayment")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("minimum_payment");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<int>("PaymentType")
                        .HasColumnType("integer")
                        .HasColumnName("payment_type");

                    b.Property<int?>("Period")
                        .HasColumnType("integer")
                        .HasColumnName("period");

                    b.Property<int>("Periodicity")
                        .HasColumnType("integer")
                        .HasColumnName("periodicity");

                    b.Property<int>("Regime")
                        .HasColumnType("integer")
                        .HasColumnName("regime");

                    b.Property<Guid>("schedule_id")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.HasKey("Id");

                    b.HasIndex("schedule_id");

                    b.ToTable("payment_deadlines", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Tax.Obligations.TaxObligationSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<int?>("FiscalYear")
                        .HasColumnType("integer")
                        .HasColumnName("fiscal_year");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("name");

                    b.Property<Guid>("tax_rule_id")
                        .HasColumnType("uuid")
                        .HasColumnName("tax_rule_id");

                    b.HasKey("Id");

                    b.HasIndex("tax_rule_id")
                        .IsUnique();

                    b.ToTable("tax_obligation_schedules", (string)null);
                });

            modelBuilder.Entity("DeclarationDeadlineLegalReference", b =>
                {
                    b.Property<Guid>("DeclarationDeadlineId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LegalReferencesId")
                        .HasColumnType("uuid");

                    b.HasKey("DeclarationDeadlineId", "LegalReferencesId");

                    b.HasIndex("LegalReferencesId");

                    b.ToTable("declaration_deadline_legal_references", (string)null);
                });

            modelBuilder.Entity("LegalReferencePaymentDeadline", b =>
                {
                    b.Property<Guid>("LegalReferencesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PaymentDeadlineId")
                        .HasColumnType("uuid");

                    b.HasKey("LegalReferencesId", "PaymentDeadlineId");

                    b.HasIndex("PaymentDeadlineId");

                    b.ToTable("payment_deadline_legal_references", (string)null);
                });

            modelBuilder.Entity("LegalReferenceTaxObligationSchedule", b =>
                {
                    b.Property<Guid>("LegalReferencesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TaxObligationScheduleId")
                        .HasColumnType("uuid");

                    b.HasKey("LegalReferencesId", "TaxObligationScheduleId");

                    b.HasIndex("TaxObligationScheduleId");

                    b.ToTable("tax_obligation_schedule_legal_references", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Contracts.AttributeDefinition", b =>
                {
                    b.HasOne("Core.Domain.Contracts.EnumDefinition", "EnumDefinition")
                        .WithMany()
                        .HasForeignKey("EnumDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Domain.Tax.Assets.AssetType", null)
                        .WithMany("ExpectedAttributes")
                        .HasForeignKey("asset_type_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnumDefinition");
                });

            modelBuilder.Entity("Core.Domain.Contracts.EnumItem", b =>
                {
                    b.HasOne("Core.Domain.Contracts.EnumDefinition", "EnumDefinition")
                        .WithMany("Items")
                        .HasForeignKey("EnumDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnumDefinition");
                });

            modelBuilder.Entity("Core.Domain.Tax.Calculation.TaxRule", b =>
                {
                    b.HasOne("Core.Domain.Tax.Assets.AssetType", null)
                        .WithMany("TaxRules")
                        .HasForeignKey("asset_type_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Domain.Tax.Obligations.DeclarationDeadline", b =>
                {
                    b.HasOne("Core.Domain.Tax.Obligations.TaxObligationSchedule", null)
                        .WithMany("DeclarationDeadlines")
                        .HasForeignKey("schedule_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Core.Domain.Tax.Penalties.PenaltyDefinition", "PenaltyDefinition", b1 =>
                        {
                            b1.Property<Guid>("DeclarationDeadlineId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("AnnualRate")
                                .HasColumnType("numeric")
                                .HasColumnName("penalty_annual_rate");

                            b1.Property<decimal?>("Cap")
                                .HasColumnType("numeric")
                                .HasColumnName("penalty_cap");

                            b1.Property<bool>("Capitalize")
                                .HasColumnType("boolean")
                                .HasColumnName("penalty_capitalize");

                            b1.Property<decimal>("FixedAmount")
                                .HasColumnType("numeric")
                                .HasColumnName("penalty_fixed_amount");

                            b1.Property<string>("GracePeriod")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("penalty_grace_period");

                            b1.Property<decimal?>("Minimum")
                                .HasColumnType("numeric")
                                .HasColumnName("penalty_minimum");

                            b1.Property<string>("Period")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("penalty_period");

                            b1.Property<decimal>("PeriodRate")
                                .HasColumnType("numeric")
                                .HasColumnName("penalty_period_rate");

                            b1.Property<decimal>("PeriodRateIncrement")
                                .HasColumnType("numeric")
                                .HasColumnName("penalty_period_rate_increment");

                            b1.Property<int>("TriggerEvent")
                                .HasColumnType("integer")
                                .HasColumnName("penalty_trigger_event");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasColumnName("penalty_type");

                            b1.HasKey("DeclarationDeadlineId");

                            b1.ToTable("declaration_deadlines");

                            b1.WithOwner()
                                .HasForeignKey("DeclarationDeadlineId");
                        });

                    b.Navigation("PenaltyDefinition");
                });

            modelBuilder.Entity("Core.Domain.Tax.Obligations.PaymentDeadline", b =>
                {
                    b.HasOne("Core.Domain.Tax.Obligations.TaxObligationSchedule", null)
                        .WithMany("PaymentDeadlines")
                        .HasForeignKey("schedule_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Core.Domain.Tax.Penalties.PenaltyDefinition", "PenaltyDefinition", b1 =>
                        {
                            b1.Property<Guid>("PaymentDeadlineId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("AnnualRate")
                                .HasColumnType("numeric")
                                .HasColumnName("penalty_annual_rate");

                            b1.Property<decimal?>("Cap")
                                .HasColumnType("numeric")
                                .HasColumnName("penalty_cap");

                            b1.Property<bool>("Capitalize")
                                .HasColumnType("boolean")
                                .HasColumnName("penalty_capitalize");

                            b1.Property<decimal>("FixedAmount")
                                .HasColumnType("numeric")
                                .HasColumnName("penalty_fixed_amount");

                            b1.Property<string>("GracePeriod")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("penalty_grace_period");

                            b1.Property<decimal?>("Minimum")
                                .HasColumnType("numeric")
                                .HasColumnName("penalty_minimum");

                            b1.Property<string>("Period")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("penalty_period");

                            b1.Property<decimal>("PeriodRate")
                                .HasColumnType("numeric")
                                .HasColumnName("penalty_period_rate");

                            b1.Property<decimal>("PeriodRateIncrement")
                                .HasColumnType("numeric")
                                .HasColumnName("penalty_period_rate_increment");

                            b1.Property<int>("TriggerEvent")
                                .HasColumnType("integer")
                                .HasColumnName("penalty_trigger_event");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasColumnName("penalty_type");

                            b1.HasKey("PaymentDeadlineId");

                            b1.ToTable("payment_deadlines");

                            b1.WithOwner()
                                .HasForeignKey("PaymentDeadlineId");
                        });

                    b.Navigation("PenaltyDefinition");
                });

            modelBuilder.Entity("Core.Domain.Tax.Obligations.TaxObligationSchedule", b =>
                {
                    b.HasOne("Core.Domain.Tax.Calculation.TaxRule", null)
                        .WithOne("ObligationSchedule")
                        .HasForeignKey("Core.Domain.Tax.Obligations.TaxObligationSchedule", "tax_rule_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DeclarationDeadlineLegalReference", b =>
                {
                    b.HasOne("Core.Domain.Tax.Obligations.DeclarationDeadline", null)
                        .WithMany()
                        .HasForeignKey("DeclarationDeadlineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.Tax.Obligations.LegalReference", null)
                        .WithMany()
                        .HasForeignKey("LegalReferencesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LegalReferencePaymentDeadline", b =>
                {
                    b.HasOne("Core.Domain.Tax.Obligations.LegalReference", null)
                        .WithMany()
                        .HasForeignKey("LegalReferencesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.Tax.Obligations.PaymentDeadline", null)
                        .WithMany()
                        .HasForeignKey("PaymentDeadlineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LegalReferenceTaxObligationSchedule", b =>
                {
                    b.HasOne("Core.Domain.Tax.Obligations.LegalReference", null)
                        .WithMany()
                        .HasForeignKey("LegalReferencesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.Tax.Obligations.TaxObligationSchedule", null)
                        .WithMany()
                        .HasForeignKey("TaxObligationScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Domain.Contracts.EnumDefinition", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Core.Domain.Tax.Assets.AssetType", b =>
                {
                    b.Navigation("ExpectedAttributes");

                    b.Navigation("TaxRules");
                });

            modelBuilder.Entity("Core.Domain.Tax.Calculation.TaxRule", b =>
                {
                    b.Navigation("ObligationSchedule");
                });

            modelBuilder.Entity("Core.Domain.Tax.Obligations.TaxObligationSchedule", b =>
                {
                    b.Navigation("DeclarationDeadlines");

                    b.Navigation("PaymentDeadlines");
                });
#pragma warning restore 612, 618
        }
    }
}
